import heroImage from '../../assets/social-welfare-banner.jpg';
import childEducationImage from '../../assets/education-campaign.avif';
import digitalLearningImage from '../../assets/education-day.avif';
import readingProgramImage from '../../assets/boy-reading.avif';
import publicHealthImage from '../../assets/health-campaign.jpg';
import mentalWellnessImage from '../../assets/heath-day.avif';
import livelihoodImage from '../../assets/champaign-charity.avif';
import womenLeadershipImage from '../../assets/champaign-humanity-day.avif';
import reliefOpsImage from '../../assets/campaign-1.avif';

export const courseData = [
  {
    id: 'community-volunteer-onboarding',
    title: 'Community Volunteer Onboarding',
    description: 'Foundation training for volunteers working in education, health, and local welfare camps.',
    longDescription:
      'This program prepares new volunteers to work confidently with families, schools, and local welfare teams. You will learn community engagement basics, safe conduct, field reporting, and collaboration practices for social impact programs.',
    category: 'All Programs',
    duration: '6 Weeks',
    level: 'Beginner',
    learners: 1450,
    rating: 4.8,
    startsOn: '15 May 2026',
    seats: '120 seats',
    language: 'Hindi + English',
    certificate: 'Completion Certificate',
    format: 'Online + Field Practicum',
    img: heroImage,
    outcomes: [
      'Understand core social welfare workflows and ethics',
      'Communicate effectively with beneficiaries and local partners',
      'Maintain basic field records and follow reporting standards',
      'Support campaign operations with safety and accountability',
    ],
    modules: [
      'Orientation to Social Welfare Programs',
      'Community Communication and Trust Building',
      'Field Documentation and Data Basics',
      'Volunteer Safety, Conduct, and Escalation Paths',
    ],
  },
  {
    id: 'child-education-mobilization',
    title: 'Child Education Mobilization',
    description: 'Practical methods to reduce dropout rates and improve parent-school engagement.',
    longDescription:
      'This course focuses on helping children stay in school by improving enrollment outreach, parent engagement, and school-community coordination. It includes practical tools that volunteers can apply in local neighborhoods and villages.',
    category: 'Child Protection',
    duration: '5 Weeks',
    level: 'Beginner',
    learners: 980,
    rating: 4.7,
    startsOn: '20 May 2026',
    seats: '90 seats',
    language: 'Hindi + English',
    certificate: 'Program Certificate',
    format: 'Online + Community Assignments',
    img: childEducationImage,
    outcomes: [
      'Conduct household-level enrollment outreach',
      'Identify common causes of school dropout early',
      'Run parent awareness circles with local schools',
      'Create simple child progress tracking plans',
    ],
    modules: [
      'Enrollment Mapping and Child Tracking',
      'Parent-School Engagement Techniques',
      'Learning Support for At-Risk Children',
      'Referral Pathways and Case Follow-Up',
    ],
  },
  {
    id: 'digital-learning-rural-youth',
    title: 'Digital Learning for Rural Youth',
    description: 'Design and run digital literacy sessions with low-cost devices and online tools.',
    longDescription:
      'This course enables volunteers to build digital confidence among rural youth. It covers device basics, safe internet practices, online learning tools, and practical session planning for low-resource environments.',
    category: 'Digital Literacy',
    duration: '4 Weeks',
    level: 'Intermediate',
    learners: 870,
    rating: 4.6,
    startsOn: '27 May 2026',
    seats: '75 seats',
    language: 'Hindi + English',
    certificate: 'Digital Literacy Facilitator Certificate',
    format: 'Online Workshops + Demo Labs',
    img: digitalLearningImage,
    outcomes: [
      'Deliver beginner-friendly digital literacy sessions',
      'Teach safe internet and cyber hygiene fundamentals',
      'Use free educational tools for youth learning',
      'Set up community digital support circles',
    ],
    modules: [
      'Digital Basics and Device Familiarity',
      'Safe Internet for Students and Families',
      'Online Learning Platforms and Practices',
      'Running Local Digital Help Desks',
    ],
  },
  {
    id: 'reading-mentorship-program',
    title: 'Reading Mentorship Program',
    description: 'Train volunteers to improve reading comprehension for primary school children.',
    longDescription:
      'The program trains mentors in foundational reading methods, storytelling, and comprehension-building activities. It is designed for volunteers supporting early-grade children in schools and community reading corners.',
    category: 'Child Protection',
    duration: '3 Weeks',
    level: 'Beginner',
    learners: 740,
    rating: 4.7,
    startsOn: '02 June 2026',
    seats: '100 seats',
    language: 'Hindi + English',
    certificate: 'Reading Mentor Certificate',
    format: 'Online + Practice Sessions',
    img: readingProgramImage,
    outcomes: [
      'Use storytelling to build reading interest',
      'Apply level-based reading exercises',
      'Track reading progress with simple rubrics',
      'Support children struggling with comprehension',
    ],
    modules: [
      'Foundational Literacy Concepts',
      'Storytelling and Read-Aloud Methods',
      'Assessment and Progress Logs',
      'Inclusive Classroom Reading Support',
    ],
  },
  {
    id: 'primary-health-camp-management',
    title: 'Primary Health Camp Management',
    description: 'Plan and execute village health camps with referral workflows and documentation.',
    longDescription:
      'This course equips field teams with practical systems to organize health camps, manage patient flow, coordinate referrals, and maintain records. It focuses on accessible and community-centric health outreach.',
    category: 'Public Health',
    duration: '7 Weeks',
    level: 'Intermediate',
    learners: 620,
    rating: 4.8,
    startsOn: '10 June 2026',
    seats: '70 seats',
    language: 'Hindi + English',
    certificate: 'Health Camp Operations Certificate',
    format: 'Hybrid (Online + Field)',
    img: publicHealthImage,
    outcomes: [
      'Plan outreach camps with role clarity and flow',
      'Coordinate screening, registration, and follow-up',
      'Document camp outcomes for impact reporting',
      'Link patients with nearby health services',
    ],
    modules: [
      'Camp Planning and Logistics',
      'Registration and Screening Operations',
      'Referral Networks and Follow-Up',
      'Data Recording and Reporting Standards',
    ],
  },
  {
    id: 'mental-wellness-first-response',
    title: 'Mental Wellness First Response',
    description: 'Recognize stress and provide safe, basic psycho-social support in communities.',
    longDescription:
      'This course introduces practical first-response techniques for emotional distress in communities. Participants learn safe listening, basic support methods, and referral pathways for professional care.',
    category: 'Public Health',
    duration: '4 Weeks',
    level: 'Intermediate',
    learners: 590,
    rating: 4.5,
    startsOn: '16 June 2026',
    seats: '80 seats',
    language: 'Hindi + English',
    certificate: 'Mental Wellness Support Certificate',
    format: 'Live Online Sessions',
    img: mentalWellnessImage,
    outcomes: [
      'Identify signs of distress and burnout',
      'Offer safe non-judgmental first-level support',
      'Know when and how to escalate cases',
      'Create mental wellness-safe community spaces',
    ],
    modules: [
      'Understanding Stress and Emotional Signals',
      'Active Listening and Support Conversations',
      'Risk Identification and Safety Planning',
      'Referral and Follow-Up Protocols',
    ],
  },
  {
    id: 'livelihood-planning-families',
    title: 'Livelihood Planning for Families',
    description: 'Support family income planning, skill mapping, and local job-linkage pathways.',
    longDescription:
      'Participants learn to support household livelihood planning by identifying skills, local opportunities, and job-linkage pathways. The course emphasizes dignity-first and context-specific income strategies.',
    category: 'Livelihood',
    duration: '6 Weeks',
    level: 'Intermediate',
    learners: 690,
    rating: 4.6,
    startsOn: '22 June 2026',
    seats: '85 seats',
    language: 'Hindi + English',
    certificate: 'Livelihood Facilitation Certificate',
    format: 'Online + Community Casework',
    img: livelihoodImage,
    outcomes: [
      'Map household skills and earning options',
      'Guide families in realistic income planning',
      'Connect eligible members to local opportunities',
      'Monitor progress through simple livelihood trackers',
    ],
    modules: [
      'Household Skill and Need Mapping',
      'Income Planning Frameworks',
      'Local Job and Market Linkages',
      'Monitoring Livelihood Progress',
    ],
  },
  {
    id: 'women-leadership-shg',
    title: 'Women Leadership in SHGs',
    description: 'Build confidence and governance skills for women-led self-help groups.',
    longDescription:
      'This course supports women leaders in self-help groups with practical governance, communication, and financial discipline tools. It strengthens collective decision-making and local enterprise confidence.',
    category: 'Women Empowerment',
    duration: '5 Weeks',
    level: 'Intermediate',
    learners: 730,
    rating: 4.8,
    startsOn: '30 June 2026',
    seats: '95 seats',
    language: 'Hindi + English',
    certificate: 'SHG Leadership Certificate',
    format: 'Blended Learning',
    img: womenLeadershipImage,
    outcomes: [
      'Facilitate structured SHG meetings',
      'Build group confidence in local leadership',
      'Improve savings and internal lending discipline',
      'Develop women-led action plans for local issues',
    ],
    modules: [
      'Leadership Basics in Self-Help Groups',
      'Meeting Facilitation and Group Governance',
      'Savings, Records, and Financial Practices',
      'Collective Action and Community Engagement',
    ],
  },
  {
    id: 'emergency-relief-coordination',
    title: 'Emergency Relief Coordination',
    description: 'Develop crisis-response skills for food distribution, shelter support, and records.',
    longDescription:
      'This course prepares participants for rapid, organized response during emergencies. It covers needs assessment, relief distribution workflows, shelter coordination, and responsible data practices.',
    category: 'Emergency Relief',
    duration: '4 Weeks',
    level: 'Advanced',
    learners: 510,
    rating: 4.7,
    startsOn: '08 July 2026',
    seats: '60 seats',
    language: 'Hindi + English',
    certificate: 'Relief Response Operations Certificate',
    format: 'Simulation + Field Drills',
    img: reliefOpsImage,
    outcomes: [
      'Perform rapid needs assessments',
      'Manage transparent relief distribution workflows',
      'Coordinate shelter and essential services support',
      'Maintain accurate beneficiary and stock records',
    ],
    modules: [
      'Emergency Preparedness and Rapid Assessment',
      'Relief Distribution Planning and Execution',
      'Shelter and Vulnerable Group Support',
      'Operational Reporting and Coordination',
    ],
  },
];

export const getCourseById = (id) => courseData.find((course) => course.id === id);
